[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Michał Zabielski <zabielski.michal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
